apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-proxmox-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
type: Opaque
stringData:
  PROXMOX_URL: {{ .Values.proxmox.url | quote }}
  PROXMOX_TOKEN_ID: {{ .Values.proxmox.tokenId | quote }}
  PROXMOX_SECRET: {{ .Values.proxmox.secret | quote }}
  PROXMOX_INSECURE: {{ .Values.proxmox.insecure | quote }}
  PROXMOX_NODE: {{ .Values.proxmox.node | quote }}
  PROXMOX_STORAGE: {{ .Values.proxmox.storage | quote }}
  PROXMOX_BRIDGE: {{ .Values.proxmox.bridge | quote }}
  {{- if .Values.proxmox.pool }}
  PROXMOX_POOL: {{ .Values.proxmox.pool | quote }}
  {{- end }}
  {{- if .Values.proxmox.tags }}
  PROXMOX_TAGS: {{ .Values.proxmox.tags | quote }}
  {{- end }}
