apiVersion: proxkube/v1
kind: Pod
metadata:
  name: my-web-server
  namespace: default
  labels:
    app: nginx
    env: production
spec:
  node: pve
  osTemplate: "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
  hostname: my-web-server
  unprivileged: true
  startOnBoot: true
  nameserver: "8.8.8.8"
  resources:
    cpu: 2
    memory: 512
    swap: 256
    disk: 8
    storage: local-lvm
    network:
      bridge: vmbr0
      ip: dhcp
